### ISSUE TITLE
[Vssue]Hello Beijing

### ISSUE THREAD

**Issue by patr1ckzhu** [OOXXXX/OOXXXX.github.io#3]
https://www.patrickzhu.club/posts/2019/08/01/%E6%8A%B5%E4%BA%AC.html

**Comment by Helen-dian** [comment]
我原来在北京参加作文比赛，出租车也没少打，北京大叔的单口相声真的是途中的一大乐趣了。

**Comment by OOXXXX** [comment]
@Helen-dian

> 我原来在北京参加作文比赛，出租车也没少打，北京大叔的单口相声真的是途中的一大乐趣了。

海伦优秀，小帕自愧不如
