### ISSUE TITLE
[Vssue]Goodbye Beijing

### ISSUE THREAD

**Issue by patr1ckzhu** [OOXXXX/OOXXXX.github.io#4]
https://www.patrickzhu.club/posts/2019/08/05/%E7%A6%BB%E4%BA%AC.html

**Comment by patr1ckzhu** [comment]
开始养生了✌️

**Comment by Helen-dian** [comment]
小图灵真的相当可爱了！😆

**Comment by patr1ckzhu** [comment]
@Helen-dian

> 小图灵真的相当可爱了！😆

往事不堪回首...
